"""initial migration

Revision ID: c91ef6d2198c
Revises: 
Create Date: 2024-12-26 15:52:05.578415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c91ef6d2198c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_data',
    sa.Column('condition_code', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('localtime', sa.DateTime(), nullable=False),
    sa.Column('temp_c', sa.Float(), nullable=False),
    sa.Column('wind_kph', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('feelslike_c', sa.Float(), nullable=False),
    sa.Column('cloud', sa.Float(), nullable=False),
    sa.Column('condition', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('condition_code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('weather_data1',
    sa.Column('condition_code', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('temp_c', sa.String(length=100), nullable=False),
    sa.Column('wind_kph', sa.String(length=100), nullable=False),
    sa.Column('humidity', sa.String(length=100), nullable=False),
    sa.Column('feelslike_c', sa.String(length=100), nullable=False),
    sa.Column('condition', sa.String(length=100), nullable=False),
    sa.Column('condition_icon', sa.String(length=100), nullable=True),
    sa.Column('localtime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name', 'condition_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weather_data1')
    op.drop_table('weather_data')
    # ### end Alembic commands ###
